#!/usr/bin/env python3
"""Write one Gazebo model and one world per swarm agent, into build/.

`spec/roj/05_infrastruktura_simulace.md` calls this P1 and P2. The model name
`openipc_cinewhoop` is used as an identity - it is in the world's `<include>`,
in the plugin's own topic names and in every bridge path - and the ArduPilot
plugin reads `fdm_port_in` from SDF alone (`ArduPilotPlugin.cc:1272`), with no
environment variable and no way for an `<include>` to override it. So three
instances need three models, and three models that are maintained by hand would
drift apart.

Generated, then, rather than copied: the airframe's own model is the single
source, and each agent gets the same file with two things changed, its name and
its port. The output goes under `build/`, which is git-ignored, and reaches
Gazebo through `GZ_SIM_RESOURCE_PATH` the same way `OPENIPC_AIRFRAME` already
picks a model directory.

    scripts/generate_agent_models.py --airframe pavo20 --agents 2

Prints the resource path and world path the caller needs to export.
"""

import argparse
import os
import re
import shutil
import sys

# Where the agents stand at the start of a run. From spec/roj/08_rozhodnuti.md
# R15: one launch spot, the agents in a row 0.8 m apart - just outside d_safe
# (0.78 m at 0.5 m/s), inside the 1.41 m stop line, so the swarm starts as
# a cluster and has to spread itself out, as it would from one table in a
# real room. x = 0.5 rather than 0 keeps every agent more than 1 m off the
# enclosure wall. The earlier 2 m spacing handed the swarm its separation
# before it had done anything.
START_POSES = [
    (0.5, -0.8, 0.035),
    (0.5, 0.0, 0.035),
    (0.5, 0.8, 0.035),
]

# A world that moves the enclosure off that row gets its own, same spacing.
# cluttered_room_corridors.sdf: the enclosure reaches x = 0.5, so the row
# moves to x = 2.0 - 1.5 m off the enclosure, 2.0 m short of the x+ wall the
# agents face, and from y = 0 up, clear of the pillar at y = -1.5.
START_POSES_BY_WORLD = {
    "cluttered_room_corridors.sdf": [
        (2.0, 0.0, 0.035),
        (2.0, 0.8, 0.035),
        (2.0, 1.6, 0.035),
    ],
}
START_POSES_BY_WORLD["cluttered_room_complex.sdf"] = (
    START_POSES_BY_WORLD["cluttered_room_corridors.sdf"])

# SITL instance N talks JSON on 9002 + 10*N, which is what -I<N> does to the
# ports on the autopilot's side. The model has to listen where its own
# autopilot speaks.
FDM_PORT_BASE = 9002
FDM_PORT_STEP = 10


def agent_model_name(index):
    return f"openipc_cinewhoop_v{index}"


def write_model(source_dir, out_models, index, instance_base=0, camera=True):
    """One agent's model directory: same airframe, own name, own port.

    `instance_base` shifts the port the way the autopilot's -I shifts its own:
    two swarms flown side by side (OPENIPC_SLOT) use instances 0-2 and 3-5,
    and each model has to listen where its own autopilot speaks.
    """
    name = agent_model_name(index)
    target = os.path.join(out_models, name)
    os.makedirs(target, exist_ok=True)

    sdf = open(os.path.join(source_dir, "model.sdf")).read()
    sdf, models_renamed = re.subn(r'<model name="openipc_cinewhoop">',
                                  f'<model name="{name}">', sdf)
    if models_renamed != 1:
        sys.exit(f"{source_dir}/model.sdf has {models_renamed} model names to "
                 "rename, expected exactly one.")

    # The name is not only the model's; it is wired into the plugins inside it.
    # Each motor subscribes under <robotNamespace>, and the ArduPilot plugin
    # publishes each rotor command to a <cmd_topic> that names the model. Rename
    # the element and not these, and two vehicles share one set of rotor topics:
    # ArduPilot writes to a topic the actuator bridge is not reading, the motors
    # listen to a namespace nothing publishes on, and both vehicles sit on the
    # ground while every service reports success. Measured that way once.
    sdf, namespaces = re.subn(
        r"<robotNamespace>openipc_cinewhoop</robotNamespace>",
        f"<robotNamespace>{name}</robotNamespace>", sdf)
    sdf, cmd_topics = re.subn(r"/model/openipc_cinewhoop/joint/",
                              f"/model/{name}/joint/", sdf)
    if namespaces < 1 or cmd_topics < 1:
        sys.exit(f"{source_dir}/model.sdf wired {namespaces} motor namespaces "
                 f"and {cmd_topics} rotor command topics to the model name; "
                 "expected both. The plugin block changed shape.")
    port = FDM_PORT_BASE + (instance_base + index - 1) * FDM_PORT_STEP
    sdf, ports_set = re.subn(r"<fdm_port_in>\d+</fdm_port_in>",
                             f"<fdm_port_in>{port}</fdm_port_in>", sdf)
    if ports_set != 1:
        sys.exit(f"{source_dir}/model.sdf has {ports_set} fdm_port_in entries, "
                 "expected exactly one. The plugin block changed shape.")
    banner = (f"<!-- Generated by scripts/generate_agent_models.py for agent "
              f"v{index} from {source_dir}/model.sdf. Do not edit: regenerated "
              f"on every run. -->\n")
    # After the XML declaration, never before it: a comment in front of
    # `<?xml ...?>` is not valid XML, and Gazebo then fails to read the model
    # and the world that includes it, which looks like a plugin problem rather
    # than a punctuation one.
    declaration = re.match(r"<\?xml[^>]*\?>\n", sdf)
    if declaration is None:
        sys.exit(f"{source_dir}/model.sdf does not start with an XML "
                 "declaration; the generator would put its banner in the "
                 "wrong place.")
    sdf = sdf[:declaration.end()] + banner + sdf[declaration.end():]
    if not camera:
        # The mapping flies on the lidar. A 640 x 480 camera at 15 Hz per
        # agent, rendered on the laptop's integrated GPU and bridged into
        # ROS, is ~40 MB/s per swarm nobody reads; two swarms side by side
        # with it ran at a real-time factor of 0.1 (swarm_batch.py).
        sdf, cameras = re.subn(r'\s*<sensor name="front_camera" type="camera">.*?</sensor>',
                               "", sdf, flags=re.S)
        if cameras != 1:
            sys.exit(f"{source_dir}/model.sdf has {cameras} front cameras to "
                     "drop, expected exactly one.")
    with open(os.path.join(target, "model.sdf"), "w") as handle:
        handle.write(sdf)

    config = open(os.path.join(source_dir, "model.config")).read()
    config = config.replace("<name>openipc_cinewhoop</name>",
                            f"<name>{name}</name>")
    with open(os.path.join(target, "model.config"), "w") as handle:
        handle.write(config)
    return name, port


def write_world(base_world, out_worlds, names):
    """The base world with its one vehicle replaced by several, spread out."""
    world = open(base_world).read()
    include = re.search(
        r"[ \t]*<include>\s*<uri>model://openipc_cinewhoop</uri>\s*"
        r"<pose>[^<]*</pose>\s*</include>\n", world)
    if include is None:
        sys.exit(f"No single-vehicle <include> found in {base_world}; the "
                 "world no longer has the shape this generator edits.")
    if len(names) > len(START_POSES):
        sys.exit(f"{len(names)} agents asked for, {len(START_POSES)} start "
                 "poses written down. Add poses to START_POSES deliberately - "
                 "they are a decision about separation, not a loop index.")

    blocks = []
    for name, (x, y, z) in zip(names, START_POSES):
        blocks.append("    <include>\n"
                      f"      <uri>model://{name}</uri>\n"
                      f"      <pose>{x} {y} {z} 0 0 0</pose>\n"
                      "    </include>\n")
    world = world[:include.start()] + "".join(blocks) + world[include.end():]

    os.makedirs(out_worlds, exist_ok=True)
    stem = os.path.splitext(os.path.basename(base_world))[0]
    path = os.path.join(out_worlds, f"{stem}_x{len(names)}.sdf")
    with open(path, "w") as handle:
        handle.write(world)
    return path



def write_bridge_config(out_root, world_name, names, camera=True):
    """One ros_gz_bridge config per agent, derived from the single-drone one.

    The template in `config/gz_bridge.yaml` is the source, not a second copy:
    it already carries `@world@` for the world the sensors are scoped to, and
    the rest of each topic path is the model name, which is exactly what
    differs per agent. Substituting here rather than adding placeholders to
    the template keeps the fourteen single-drone check scripts working
    unchanged - they render the template with `sed s/@world@/.../` and know
    nothing about agents.

    The ROS side is renamed too: `/openipc_cinewhoop/scan/front` becomes
    `/v1/scan/front`, which is the namespace `spec/roj/04_rozhrani.md` gives
    each agent.
    """
    template = open("ros_ws/src/openipc_cinewhoop_gazebo/config/gz_bridge.yaml").read()
    paths = []
    os.makedirs(out_root, exist_ok=True)
    for index, name in enumerate(names, start=1):
        text = template.replace("@world@", world_name)
        if index > 1:
            # /clock belongs to the world, not to an agent. Three bridges
            # forwarding it would be three publishers on one topic, which is
            # a race to be the one a subscriber happens to hear.
            text = re.sub(r'- ros_topic_name: "/clock".*?direction: GZ_TO_ROS\n',
                          "", text, flags=re.S)
        if not camera:
            text = re.sub(r'- ros_topic_name: "/openipc_cinewhoop/camera/[^"]*".*?direction: GZ_TO_ROS\n',
                          "", text, flags=re.S)
        text = text.replace("/model/openipc_cinewhoop/", f"/model/{name}/")
        text = text.replace('"/openipc_cinewhoop/', f'"/v{index}/')
        path = os.path.join(out_root, f"gz_bridge_v{index}.yaml")
        with open(path, "w") as handle:
            handle.write(text)
        paths.append(path)
    return paths


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--airframe", default=os.environ.get(
        "OPENIPC_AIRFRAME", "cinewhoop"))
    parser.add_argument("--agents", type=int, default=2)
    parser.add_argument("--world", default="room_test.sdf")
    parser.add_argument("--out", default="build/agent_sim")
    parser.add_argument("--instance-base", type=int, default=0)
    parser.add_argument("--no-camera", action="store_true",
                        help="drop the front camera from the models and the "
                        "bridge (the lidar mapping does not use it)")
    args = parser.parse_args()

    package = "ros_ws/src/openipc_cinewhoop_gazebo"
    models_dir = ("models" if args.airframe == "cinewhoop"
                  else f"models_{args.airframe}")
    source_dir = os.path.join(package, models_dir, "openipc_cinewhoop")
    if not os.path.isdir(source_dir):
        sys.exit(f"No model directory {source_dir} for airframe "
                 f"{args.airframe!r}.")
    # A path to a world of its own (scripts/random_world.py writes them under
    # logs/), or the name of one of the package's.
    base_world = (args.world if os.path.isabs(args.world)
                  else os.path.join(package, "worlds", args.world))
    global START_POSES
    START_POSES = START_POSES_BY_WORLD.get(args.world, START_POSES)
    # A generated world says where its agents start, because only the
    # generator knows where it left room for them.
    if os.path.isfile(base_world):
        written = re.search(r"START_POSES\s+([-\d.,\s]+?)\s*-->",
                            open(base_world).read())
        if written:
            START_POSES = [tuple(float(v) for v in pose.split(",")) + (0.035,)
                           for pose in written.group(1).split()]
    if not os.path.isfile(base_world):
        sys.exit(f"No world {base_world}.")

    out_root = os.path.join(args.out, args.airframe)
    out_models = os.path.join(out_root, "models")
    # Regenerated from scratch every time. A stale model from a previous run
    # with a different agent count is a vehicle that answers on a port nobody
    # is talking to, and it would be found by watching it sit still.
    shutil.rmtree(out_models, ignore_errors=True)

    names = []
    for index in range(1, args.agents + 1):
        name, port = write_model(source_dir, out_models, index,
                                 args.instance_base, not args.no_camera)
        names.append(name)
        print(f"  {name}: fdm_port_in {port}, start "
              f"{START_POSES[index - 1]}")
    world_path = write_world(base_world, os.path.join(out_root, "worlds"), names)

    # The world's own name, read from the file rather than from its filename,
    # for the same reason gazebo.launch.py does: a file and a world that
    # disagree should fail loudly instead of bridging nothing.
    world_name = re.search(r'<world\s+name="([^"]+)"', open(world_path).read())
    if world_name is None:
        sys.exit(f"No <world name=...> in {world_path}.")
    bridges = write_bridge_config(os.path.join(out_root, "bridge"),
                                  world_name.group(1), names, not args.no_camera)

    # Each agent's EKF origin is where it starts, so these are what moves its
    # pose and its map into the room. The coordinator takes them as one flat
    # list, x and y per agent, in the order of the names.
    print("offsets " + " ".join(f"{x} {y}" for x, y, _ in
                                START_POSES[:len(names)]))
    print(f"models {os.path.abspath(out_models)}")
    print(f"world {os.path.abspath(world_path)}")
    for path in bridges:
        print(f"bridge {os.path.abspath(path)}")


if __name__ == "__main__":
    main()
